# Generated by Django 5.1.4 on 2025-01-10 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = []

  operations = [
    migrations.CreateModel(
        name="ChatRecord",
        fields=[
          (
            "id",
            models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
          ),
          ("user_message", models.TextField()),
          ("bot_response", models.TextField()),
          ("context", models.TextField()),
          ("created_at",
           models.DateTimeField(default=django.utils.timezone.now)),
        ],
    ),
  ]
