# Generated by Django 5.1.4 on 2025-01-10 01:49

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = []

  operations = [
    migrations.CreateModel(
        name="TransportationData",
        fields=[
          (
            "id",
            models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
          ),
          ("district", models.CharField(max_length=100)),
          ("green_transport", models.FloatField()),
          ("public_transport", models.FloatField()),
          ("non_motorized", models.FloatField()),
          ("walking", models.FloatField()),
          ("bike", models.FloatField()),
          ("private_motorized", models.FloatField()),
          ("most_used_public_transport", models.FloatField()),
          ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
        ],
    ),
  ]
